### ISSUE TITLE
Preprocess ThermoScenes data

### ISSUE THREAD

**Issue by Neal2020GitHub** [mzzcdf/Thermal3DGS#2]
Hi, authors! 

Thanks for open-sourcing your work! 

May I know how you preprocess ThermoScenes data for training? Thank you.

**Comment by PuppetCQ** [comment]
> Hi, authors!
> 
> Thanks for open-sourcing your work!
> 
> May I know how you preprocess ThermoScenes data for training? Thank you.

First, we cannot use the convert.py in 3DGS directly on the original thermal image of ThermoScenes to get the corresponding file. This is because, on the one hand, the thermal image features of ThermoScenes are not obvious, and COLMAP cannot successfully obtain the camera pose (the original text should be the camera pose obtained by running the visible light image); on the other hand, the re-running camera pose is different, and the comparison is unfair. But ThermoScenes provides the camera pose of the COLMAP run, which is located in the "colmap" folder. This has gone through Feature extraction, Feature matching and Bundle adjustment. This is the same as the first few steps of convert.py in 3DGS, which means that we can use this folder directly instead of re-running the COLMAP. Of course, we need to name this folder the name of convert.py in 3DGS, that is, "distorted". By the way, the image file extension of ThermoScenes is very confusing, and you may need to redefine the image file extension according to the COLMAP run results provided by ThermoScenes.
